USE DB_RH
GO

SELECT * FROM TB_AREAS
SELECT * FROM TB_CARGOS

--1. LISTAR TODAS AS ÁREAS QUE POSSUEM UM CARGO CORRESPONDENTE CADASTRADO
SELECT * FROM TB_AREAS WHERE ID IN (SELECT ID_AREA FROM TB_CARGOS)

--2. LISTAR TODAS AS ÁREAS QUE NÃO POSSUEM UM CARGO CORRESPONDENTE CADASTRADO
SELECT * FROM TB_AREAS WHERE ID NOT IN (SELECT ID_AREA FROM TB_CARGOS)

--3. BUSCAR TODOS OS CARGOS CUJO ID ESTEJA NO INTERVALO ENTRE 3 E 5
SELECT * FROM TB_CARGOS WHERE ID BETWEEN 3 AND 5
SELECT * FROM TB_CARGOS WHERE ID = 3 OR ID = 4 OR ID = 5
SELECT * FROM TB_CARGOS WHERE ID IN (3, 4, 5)

--4. LISTAR TODOS OS CANDIDATOS QUE AINDA NÃO SE INSCREVERAM EM NENHUMA VAGA
SELECT * FROM TB_CANDIDATOS WHERE CPF NOT IN (SELECT CPF FROM TB_INSCRICOES)