USE DB_RH
GO

--1. REMOVENDO UMA ÁREA  QUE TENHA UM CARGO CADASTRADO
DELETE FROM TB_AREAS WHERE ID = 2

--2. REMOVENDO UMA ÁREA  QUE NÃO TENHA UM CARGO CADASTRADO
DELETE FROM TB_AREAS WHERE ID = 1

--3 REMOVENDO TODAS AS ÁREAS QUE NÃO POSSUEM UM CARGO ASSOCIADO
-- (ISSO INCLUI AS ÁREAS REPETIDAS)
DELETE FROM TB_AREAS WHERE ID NOT IN (SELECT ID_AREA FROM TB_CARGOS)

