USE DB_RH
GO

--1. BUSCANDO AS INFORMAÇÕES: AREA, CARGO E SALARIO.
-- USAREMOS DUAS TABELAS, COM SEUS NOMES COMPLETOS (NÃO FAÇA ISSO EM CASA)
SELECT
	TB_AREAS.DESCRICAO AS AREA,
	TB_CARGOS.DESCRICAO AS CARGO,
	TB_CARGOS.SALARIO AS SALARIO
FROM
	TB_AREAS, TB_CARGOS
WHERE 
	TB_AREAS.ID = TB_CARGOS.ID_AREA



--2. O MESMO EXEMPLO ANTERIOR, USANDO ALIASES PARA AS TABELAS
SELECT
	A.DESCRICAO AS AREA,
	C.DESCRICAO AS CARGO,
	C.SALARIO AS SALARIO
FROM
	TB_AREAS A, TB_CARGOS C
WHERE 
	A.ID = C.ID_AREA



--3. USO DE JOINS
--- a. JOIN ou INNER JOIN
SELECT
	A.DESCRICAO AS AREA,
	C.DESCRICAO AS CARGO,
	C.SALARIO AS SALARIO
FROM
	TB_AREAS A JOIN TB_CARGOS C
ON 
	A.ID = C.ID_AREA

-- OUTRO EXEMPLO: CANDIDATOS E SUAS INSCRIÇÕES
-- MOSTRAR O CPF E O NOME DO CANDIDATO, ALÉM DA DATA DE INSCRIÇÃO:
-- CPF       CANDIDATO       DATA INSCRIÇÃO

SELECT
	CD.CPF AS CPF, 
	CD.NOME AS CANDIDATO, 
	IC.DATA_INSCRICAO AS [DATA INSCRIÇÃO]

FROM
	TB_CANDIDATOS CD INNER JOIN TB_INSCRICOES IC

ON
	CD.CPF = IC.CPF


--BUSCANDO TODOS OS CANDIDATOS E AS DATAS DE INSCRIÇÃO, MESMO OS CANDIDATOS
--QUE NÃO FIZEREM INSCRIÇÃO (NESTE CASO, DEVEMOS PRIORIZAR A TABELA TB_CANDIDATOS:
--SE ESTA TABELA ESTIVER DO LADO ESQUERDO, USAMOS LEFT JOIN)
SELECT
	CD.CPF AS CPF, 
	CD.NOME AS CANDIDATO, 
	IC.DATA_INSCRICAO AS [DATA INSCRIÇÃO]

FROM
	TB_CANDIDATOS CD LEFT JOIN TB_INSCRICOES IC

ON
	CD.CPF = IC.CPF


-- DE FORMA ANÁLOGA, PODEMOS USAR RIGHT JOIN, PRIORIZANDO A 
--TABELA DA DIREITA. NESTE CASO, A ORDEM É RELEVENTE
SELECT
	CD.CPF AS CPF, 
	CD.NOME AS CANDIDATO, 
	IC.DATA_INSCRICAO AS [DATA INSCRIÇÃO]

FROM
	TB_INSCRICOES IC RIGHT JOIN TB_CANDIDATOS CD

ON
	CD.CPF = IC.CPF

-- APLICANDO JOINS ENTRE TRÊS TABELAS
SELECT
	A.DESCRICAO AS AREA,
	C.DESCRICAO AS CARGO,
	I.DATA_INSCRICAO AS [DATA INSCIÇÃO],
	CD.NOME AS CANDIDATO,
	CD.TELEFONE

FROM
	TB_AREAS A INNER JOIN TB_CARGOS C
		ON A.ID = C.ID_AREA
	INNER JOIN TB_INSCRICOES I
		ON C.ID = I.ID_CARGO
	INNER JOIN TB_CANDIDATOS CD 
		ON I.CPF = CD.CPF


--Outro exemplo: Candidatos e suas inscrições
SELECT
	A.DESCRICAO AS AREA,
	--C.ID_AREA AS AREA,
	C.DESCRICAO AS CARGO,
	CONVERT(VARCHAR(10), I.DATA_INSCRICAO, 103) AS [DATA INSCIÇÃO],
	CD.NOME AS CANDIDATO,
	CD.TELEFONE

FROM
	TB_AREAS A FULL JOIN TB_CARGOS C
		ON A.ID = C.ID_AREA
	FULL JOIN TB_INSCRICOES I
		ON C.ID = I.ID_CARGO
	FULL JOIN TB_CANDIDATOS CD 
		ON I.CPF = CD.CPF


